image: registry.gitlab.com/agilefactory/witboost.mesh/provisioning/cdp/cicd/scala-sbt

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY} --profile default
    - aws configure set aws_secret_access_key ${AWS_SECRET_KEY} --profile default
    - aws configure set region eu-west-1 --profile default
    - aws s3 cp artifacts/*.py s3://${{ values.bucket }}/${{ values.domain }}/${{ values.dataproduct }}/0.0.0/
  only:
    refs:
      - main